### ISSUE TITLE
[GL] gl_skymode 3 needs to be more proportional

### ISSUE THREAD

**Issue by bkoropoff** [kraflab/dsda-doom#340] opened 2023-04-09 01:12 UTC
Just noticed this.  Indexed light mode, `gl_skymode 0`.  Turning on mouselook makes the sky go nuts:

![doom00](https://user-images.githubusercontent.com/2101303/230749217-445a3a97-699a-4059-98f8-611fc8c114d2.png)
![doom01](https://user-images.githubusercontent.com/2101303/230749219-39143580-4561-4f9d-8acd-ead4f243f7a2.png)

**Comment by kraflab** [comment] 2023-04-09 10:06
I can't reproduce a problem. Related to mode 3 (which is used when mouselook is on while in mode 0). The sky does look different with mouselook because it needs to support looking up, but it looks as expected. It's not completely clear in the screenshot if this is "normal" or not to be honest 😅 

Does this look different for you in 0.25.6 in shaders mode for instance?

**Comment by bkoropoff** [comment] 2023-04-09 10:32
It looks like the sky texture has drooped, leaving a patch of solid color above:

![image](https://user-images.githubusercontent.com/2101303/230767734-8f7caf48-79d6-439a-ab71-7dc9c14e4e3a.png)

I'll try 0.25.6

**Comment by bkoropoff** [comment] 2023-04-09 10:40
0.25.6 does the same thing with skymode=3.  I guess it just looks... ugly.

**Comment by kraflab** [comment] 2023-04-09 11:07
There isn't really a perfect answer here because you either have to warp the sky texture or fill in space in some other way (or drag it, which is what happens if you force sky mode 2). I am considering capping the vertical look, which limits the perspective to only a small amount of filled in space (you can check this in heretic, which is currently capped). I can tell you though that there are people that do like mode 3 and it was specifically requested to also support this in indexed mode. Although as you know I'm not against replacing things, this one is super subjective and I'd lean on leaving it alone for the time being.

**Comment by kraflab** [comment] 2023-04-09 11:11
Btw, gzdoom:
![Screenshot 2023-04-09 131235](https://user-images.githubusercontent.com/25529060/230769145-704b1c95-2524-4de0-ab5a-32c4d7a5a3e6.png)

**Comment by bkoropoff** [comment] 2023-04-09 14:33
I'll have to take a look at how UV coordinates are generated and see if a different mapping onto the sphere looks more natural.

**Comment by andrey-budko** [comment] 2023-04-10 02:59
I like skymode=3, it was ported from gzdoom. Probably you'd like Edge's method, but I don't like it at all

https://i.imgur.com/A4RDSez.png

**Comment by kraflab** [comment] 2023-04-14 11:15
Closing this one since I also like skymode 3. If you want to experiment with a different mapping feel free to create a PR - although I will warn you in advance that I'm biased towards having fewer options in gl in order to maintain a lower surface area for regressions.

**Closed as completed by kraflab** 2023-04-14 11:15 UTC

**Comment by bkoropoff** [comment] 2023-04-16 11:22
OK, it's actually skymode 2 that is wrong (I think) at FOVs over 90
