### ISSUE TITLE
Suggestion: make full freelook possible in Heretic and Hexen

### ISSUE THREAD

**Issue by mooreye** [kraflab/dsda-doom#475] opened 2024-01-21 22:28 UTC
In Doom, with freelook enabled, you can look a full 90° up and down. In Heretic and Hexen however, you can only look about 40° up and down. In those games however looking up and down is actually a part of the vanilla gameplay and it changes how weapons fire. However, with freelook players would expect to be able to freely look full 90° just like in Doom. I suggest to make this full freelook possible while still keeping the weapons to behave within this ≈40° constraint, similarly to how the weapons in Doom always fire exactly forwards no matter how far up/down you look.

**Comment by kraflab** [comment] 2024-03-20 08:13
There's going to be a complete rewrite of how free look works in the port for the next major release, and I'll be reexamining this topic then, so it might be updated to work the same as it does in doom currently. I will close this issue for now though, because this is the intended behavior and the eventual rework will be a new foundation to work off of.

**Closed as completed by kraflab** 2024-03-20 08:13 UTC
